### ISSUE TITLE
Indicate Login Failure in BE Login

### ISSUE THREAD

**Issue by hannesbochmann** [pgampe/authenticator#13]
When the entered code is not valid there is no indication of an error. Maybe an error message should be displayed similar to the standard login. Furthermore it would be very useful if at least the HTML commend  would be present upon an invalid login. This can be used for example for a brute force protection with ModSecurity. Otherwise it's hard to tell if the login failed or not.

**Comment by hannesbochmann** [comment]
If you like I can provide a pull request.

**Comment by pgampe** [comment]
Yes please

**Comment by pgampe** [comment]
Fixed in latest release.
