### ISSUE TITLE
Class 'OTPHP\TOTP' not found

### ISSUE THREAD

**Issue by HamburgerJungeJr** [pgampe/authenticator#16]
Hi,

I installed your extension and configured it to use it with my backend account. 
But if I try to log in (after typing my password) I get an error saying "Class 'OTPHP\TOTP' not found".

How can I fix this?

**Comment by safersurfing** [comment]
Same with me here. Typo3 7.6.12. PHP7

**Comment by pgampe** [comment]
Try do download the composer.json and put it into a the extension folder.

**Comment by pgampe** [comment]
The new TER release 0.1.2 should fix this now be including the composer.json file. Please test the new release and reopen the issue if the problem persists.
