### ISSUE TITLE
QR Code not showing

### ISSUE THREAD

**Issue by safersurfing** [pgampe/authenticator#17]
With the new version I cannot see the QR code.
I have actiavted QR showing in the backend extension configuration. Have ticked the 2FA box in the user settings, but know where is the QR code showing.
After saving I am presented when login in a requested token, but I had not seen a QR code anywhere.
![3](https://cloud.githubusercontent.com/assets/16236460/20237719/b2867586-a8da-11e6-9992-b1062c4e354f.jpg)
![2](https://cloud.githubusercontent.com/assets/16236460/20237720/b286b55a-a8da-11e6-974e-5df2138efdaa.jpg)
![1](https://cloud.githubusercontent.com/assets/16236460/20237721/b29bb716-a8da-11e6-9d89-5bc56dcc183f.png)

**Comment by pgampe** [comment]
This is a bug. Same as #4 

Please disable 2 factor again (either via database `be_users.tx_authenticator_enabled` or via another user). Then safe your user settings once before activating the QR code.

I should really create a wizard for activation that checks the successful QR code entering first before locking the backend.

**Comment by safersurfing** [comment]
I can see it now in user settings, had not looked there first.
I have 4 useraccounts. 2 work perfect the other 2 not. What could the reason be.
In fact those that do not work are accounts where I have the same name in another typo3 sandbox installation under same domain, but with a subdomain name at the beginning. Could that be the reason there is a problem?

**Comment by safersurfing** [comment]
OK, it is really the case. The username has to be different then it works.
