### ISSUE TITLE
Secret is not shown

### ISSUE THREAD

**Issue by ewokhias** [pgampe/authenticator#21]
After a fresh install of TYPO3 8.6.0 on a Linux machine (Debian 8.7, PHP 7.0.16 and mysql 5.5.54) and the extension authenticator, no secret (and QR) is shown in the backend user settings. 

![authenticator_secret_missing](https://cloud.githubusercontent.com/assets/18421621/23272904/47481dbe-f9fd-11e6-92de-3b7f1edf0da7.JPG)

**Comment by pgampe** [comment]
Please save the backend user settings once.

**Comment by ewokhias** [comment]
That actually did the trick - thanks!
But first I had another problem: I was editing someone else's user settings, therefore the secret (and QR) wasnt'shown (as expected).
