### ISSUE TITLE
Call to a member function getModuleData() on a non-object (NULL)

### ISSUE THREAD

**Issue by ewokhias** [pgampe/authenticator#22]
I have an existing TYPO3 installation and wanted to add two factor authentication via authenticator. 
Installation of the extension works fine, the secret and QR code are shown.
After activation of two factor authentication in user settings, I get the following output:

```��][��6�~vW�`�r�ɶ$�w�ݝ�%�q�N�ݝ�݊S*\մ%QCR}��پ�������}
...```

After deactivation of the two factor authentication, the TYPO3-Log shows the following error:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function getModuleData() on a non-object (NULL) | BadMethodCallException thrown in file /..../typo3/sysext/backend/Classes/Utility/BackendUtility.php in line 3413. Requested URL: http://DOMAIN/index.php`

What are the server requirements? Currently the server configuration consists of:
* Apache 2.2.24
* PHP 5.6.99-hhvm
* MySql 5.5.31-30.3
* TYPO3 7.6.15

**Comment by ewokhias** [comment]
Upgrading PHP from 5.6.99 to 7.0.16 seems to fix the problem.
If PHP 5.5/5.6 is not supported, please add PHP >= 7.0 (7.1 warning: be aware of https://forge.typo3.org/issues/79183) as a requirement.

**Comment by pgampe** [comment]
I am not sure what exactly cause the problem, but would you care to provide a pull request for the PHP 7 requirement?

**Comment by taalas** [comment]
This happens on my installation as well (TYPO3 7 on PHP5) but only if enabled for a frontend user. Backend login works fine...

**Comment by pgampe** [comment]
BackendUtility only works in the Backend oviously. The whole frontend part is more a prove of concept. I suggest that you create your own auth hook based on the provided one in order to make an own form/HTML.

**Comment by ewokhias** [comment]
Sorry for my late response.
I triet to reproduce the error in https://github.com/Tuurlijk/TYPO3.Homestead for php55 and hhvm(php 5.6.99-hhvm), but didn't succeed. Everything works as expected. 
Maybe something else was causing the error on that specific server and upgrading to php 7.0 magically solved it.
@pgampe Unless someone else is able to reproduce the error, I'm closing this issue, okay?
